test_menu/food_delivery/urls.py
from django.urls import path
from . import views

app_name = 'food_delivery'

urlpatterns = [
    path('', views.index, name='index'),
    path('history/', views.history, name='history'),
    path('reportDates/', views.reportDates, name='reportDates'),
    path('report/<date>', views.report, name='report'),
]

test_menu/test_menu/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('food_delivery.urls', namespace='food_delivery'))
]

test_menu/food_delivery/models.py
from django.db import models


class Employee(models.Model):
    """Модель сотрудника"""
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Dish(models.Model):
    """Модель блюда"""
    name = models.CharField(max_length=100)
    compound = models.TextField(max_length=200)
    price = models.IntegerField()

    def __str__(self):
        return f'{self.name} - {self.price}₽: {self.compound}'


class Order(models.Model):
    """Модель заказа"""
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)
    date = models.DateField()
    dish = models.ManyToManyField(Dish)

    class Meta:
        ordering = ['-date']

test_menu/food_delivery/forms.py
from django import forms
from .models import Order


class OrderForm(forms.ModelForm):
    """Форма оформления заказа"""
    class Meta:
        model = Order

        fields = ['employee', 'date', 'dish']
        labels = {
            'employee': 'Имя сотрудника',
            'date': 'Дата',
            'dish': 'Блюдо',
        }
        widgets = {
            'employee': forms.RadioSelect,
            'date': forms.DateInput(attrs={'type': 'date', 'id': "date"}),
            'dish': forms.CheckboxSelectMultiple(),
        }

test_menu/food_delivery/views.py
from django.shortcuts import render, redirect
from .models import Dish, Order
from .forms import OrderForm


def index(request):
    """View функция страницы с формой"""
    dishes = Dish.objects.all()
    form = OrderForm(request.POST)
    context = {
        'form': form,
        'dishes': dishes,
    }
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect('food_delivery:history')
        else:
            return render(request, 'index.html', context)
    return render(request, 'index.html', context)


def history(request):
    """View функция страницы с историей заказов"""
    orders = Order.objects.all()
    context = {
        'orders': orders,
    }
    return render(request, 'history.html', context)


def reportDates(request):
    """View функция страницы со всеми отчётами"""
    dates = Order.objects.values_list('date', flat=True).distinct()
    context = {
        'dates': dates,
    }
    return render(request, 'reportDates.html', context)


def report(request, date):
    """View функция страницы с отчетом заказа еды на дату"""
    orders = Order.objects.filter(date=date)
    dishes_count = {}
    total_price = 0
    for order in orders:
        for dish in order.dish.all():
            if dish in dishes_count:
                count += 1
                dishes_count[dish] = {count: int(dish.price) * count}
            else:
                count = 1
                dishes_count[dish] = {count: int(dish.price) * count}
            total_price += int(dish.price)
    context = {
        'dishes_count': dishes_count,
        'total_price': total_price,
        'date': date,
    }
    return render(request, 'report.html', context)

test_menu/templates/history.html
{% extends 'includes/base.html' %}

{% block title %}
История заказов
{% endblock %}

{% block content %}
    <div>
        <div class="container mt-1 mb-3">
            <h1>
                История заказов
            </h1>
        </div>
        <div class="container">
            <table class="table table-striped">
                <thead>
                    <tr>
                      <th scope="col">Дата</th>
                      <th scope="col">Имя сотрудника</th>
                      <th scope="col">Блюда</th>
                    </tr>
                </thead>
                <tbody>
                    {% for order in orders %}
                        <tr>
                            <th scope="row">{{ order.date|date:"d E Y" }}</th>
                            <td>{{ order.employee }}</td>
                            <td>
                                {% for dish in order.dish.all %}
                                    {{ dish }}
                                    <br>
                                {% endfor %}
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

test_menu/templates/includes/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
        Заголовок
        {% endblock %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
    {% include 'includes/header.html' %}
    <main> 
        {% block content %}
        Контента нет
        {% endblock %}
    </main>       
    {% include 'includes/footer.html' %}
</body>
</html>

test_menu/templates/includes/footer.html
<footer class="border-top text-center py-3 mt-5">
    <p>© Copyright <span style="color:black">ТЕХНО</span><span style="color:blue">ВИЗОР</span></p>    
</footer> 

test_menu/templates/includes/header.html
<header>
  <nav class="navbar navbar-expand-lg bg-body-tertiary bg-light" >
    <div class="container">
      <a class="navbar-brand" href="#">
        <img src="https://техновизор.рф/img/logo.png" alt="Техновизор" width="104" height="40">
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Переключатель навигации">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="https://техновизор.рф">Главная</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'food_delivery:index' %}">Оформить заказ</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'food_delivery:history' %}">История заказов</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'food_delivery:reportDates' %}">Отчёты</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>

test_menu/templates/index.html
{% extends 'includes/base.html' %}

{% block title %}
Заказ еды
{% endblock %}

{% block content %}
    <div class="container">
        <div>
            <h1>
                Оформление заказа
            </h1>
            <form method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="col-2 d-grid gap-2 mx-auto">
                    <button type="submit" class="btn btn-outline-primary ">Оформить заказ</button>
                </div>
            </form>
        </div>
        <div class="mt-5">
            <div>
                <h2 class="text-center">
                    Меню:
                </h2>
            </div>
            <div class="d-flex">
                {% for dish in dishes %}
                    <div class="card mx-3" style="width: 18rem;">
                        <div class="card-body">
                            <h5 class="card-title">{{ dish.name}} </h5>
                            <p class="card-text">{{ dish.compound }}</p>
                            <h5>{{ dish.price }}₽</h5>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

test_menu/templates/report.html
{% extends 'includes/base.html' %}

{% block title %}
Отчёт
{% endblock %}

{% block content %}
    <div class="container text-center mt-1 mb-3">
        <h1>
            Отчёт за {{ date }}
        </h1>
    </div>
    <table class="table table-striped">
        <thead>
          <tr>
            <th scope="col">Блюдо</th>
            <th scope="col">Количество</th>
            <th scope="col">Цена</th>
            <th scope="col">Сумма</th>
          </tr>
        </thead>
        <tbody>
            {% for dish, countSum in dishes_count.items %}
            <tr>
                <th scope="row">{{ dish.name }}</th>
                {% for count, sum in countSum.items %}
                <td>{{ count }}</td>
                <td>{{ dish.price }}₽</td>
                <td>{{ sum }}₽</td>
                {% endfor %}
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <div class="container text-end">
        <h4>
            Общая сумма: {{ total_price }}₽
        </h4>
    </div>
{% endblock %}

test_menu/templates/reportDates.html
{% extends 'includes/base.html' %}

{% block title %}
Список отчётов
{% endblock %}

{% block content %}
    <div class="container mt-1 mb-5">
        <h1>
            Отчёты
        </h1>
    </div>
    <div class="container">
        <div class="list-group">
            {% for date in dates %}
                <a href="{% url 'food_delivery:report' date %}" class="list-group-item list-group-item-action" aria-current="true">
                    Отчет за {{ date }}
                </a>
            {% endfor %}
        </div>
    </div>
{% endblock %}